using Newtonsoft.Json;

namespace QuizGame.Connector.OpenTDB;

/// <summary>
///     Structured API response for the OpenTDB API
/// </summary>
class ApiResponse
{
    /// <summary>
    ///     The response code passed by the API.
    ///     <list>
    ///         <item>0: OK</item>
    ///     </list>
    /// </summary>
    [JsonProperty("response_code")]
    public int ResponseCode { get; set; }

    /// <summary>
    ///     A list of questions which have been generated by the API.
    /// </summary>
    [JsonProperty("results")]
    public List<OpenTDBQuestion> Results { get; set; }
}
